gestionPedidos/Pedidos/urls.py
from django.urls import path
from . import views


urlpatterns = [
    
    #Pagina Principal
    path('', views.index, name='index'),
     
    #Urls de clientes
    path('clientes/', views.ClienteListView.as_view(), name='listado_clientes'),
    path('clientes/<int:pk>/', views.ClienteDetailView.as_view(), name='cliente_detail'),
    path('clientes/<cliente_id>/pedido', views.show_pedido, name='cliente_pedido_detail'),
    path('clientes/create/', views.ClienteCreateView.as_view(), name='create_cliente'),
    path('clientes/<int:pk>/borrar/', views.ClienteDeleteView.as_view(), name='cliente_delete'),
    path('clientes/<int:pk>/editar/', views.ClienteUpdateView.as_view(), name='cliente_edit'),
    #Urls de pedidos
    path('pedidos/', views.PedidoListView.as_view(), name='listado_pedidos'),
    path('pedidos/<int:pk>', views.PedidoDetailView.as_view(), name='pedido_detail'),
    path('pedidos/create/', views.PedidoCreateView.as_view(), name='pedido_create'),
    path('pedidos/<int:pk>/borrar/', views.PedidoDeleteView.as_view(), name='pedido_delete'),
    path('pedidos/<int:pk>/editar/', views.PedidoUpdateView.as_view(), name='pedido_edit'),
    #Urls de componente
    path('componentes/', views.ComponenteListView.as_view(), name='listado_componentes'),
    path('componentes/<int:pk>', views.ComponenteDetailView.as_view(), name='componente_detail'),
    path('productos/<producto_id>/componente', views.show_producto, name='componente_producto_detail'),
    path('componentes/create/', views.ComponenteCreateView.as_view(), name='componente_create'),
    path('componentes/<int:pk>/borrar/', views.ComponenteDeleteView.as_view(), name='componente_delete'),
    path('componentes/<int:pk>/editar/', views.ComponenteUpdateView.as_view(), name='componente_edit'),
    path('api/componentes/<int:id>/', views.obtener_detalles_componente, name='api_componente'),

    #Urls de producto
    path('productos/', views.ProductoListView.as_view(), name='listado_productos'),
    path('productos/<int:pk>', views.ProductoDetailView.as_view(), name='producto_detail'),
    path('productos/create/', views.ProductoCreateView.as_view(), name='producto_create'),
    path('productos/<int:pk>/borrar/', views.ProductoDeleteView.as_view(), name='producto_delete'),
    path('productos/<int:pk>/editar/', views.ProductoUpdateView.as_view(), name='producto_edit'),
    #Urls de cantidad
    path('ProductoPedido/create/', views.ProductoPedidoCreateView.as_view(), name='ProductoPedido_create'), 
   
]

gestionPedidos/gestionPedidos/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
 path('', include('Pedidos.urls')),
 path('admin/', admin.site.urls),
]

gestionPedidos/Pedidos/models.py
from django.db import models
# Entre las clases Componente y Producto hemos elegido que tenga una relación 1-n, es decir, un componente tiene varios Productos 
# y varios productos pueden tener el mismo componente, aunque tambien podria dependiendo de quien lo piense puede ser una n-m
# que varios componentes sean de varios productos y viceversa.
class Componente(models.Model):
    componentes_codigo_referencia = models.CharField(max_length=50, unique=True)
    nombre_modelo = models.CharField(max_length=100)
    marca = models.CharField(max_length=70)
    def __str__(self):
        return self.nombre_modelo

# Clase Categiria
class Categoria(models.Model):
    categoria = models.CharField(max_length=50)

    def __str__(self):
        return self.categoria
          
# Clase producto
class Producto(models.Model):
    referencia = models.CharField(max_length=50, unique=True)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    componentes = models.ManyToManyField(Componente)

    def __str__(self):
        return f"{self.referencia}" 

#Clase cliente    
class Cliente(models.Model):
    cif = models.CharField(max_length=50)
    nombre_empresa = models.CharField(max_length=100)
    direccion = models.CharField(max_length=200)
    datos_contacto = models.CharField(max_length=200)
    def __str__(self):
        return self.nombre_empresa
    

#Clase pedido
class Pedido(models.Model):
    codigo_referencia = models.CharField(max_length=50, unique=True)
    fecha = models.DateField()
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    preciototal = models.DecimalField(max_digits=10, decimal_places=2)
    producto = models.ManyToManyField(Producto, through="ProductoPedido")
    
    def __str__(self):
        return self.codigo_referencia 


# Hemos hecho una conexion n-m para producto pedido, es decir, varios pedidos pueden ser de varios productos y viceversa
class ProductoPedido(models.Model):
    producto_solicitado = models.ForeignKey(Producto, on_delete=models.CASCADE)
    pedido_solicitado = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()
    def __str__(self):
        return f"{self.producto_solicitado} - {self.pedido_solicitado} - {self.cantidad} " 

class ProductoComponente(models.Model):
    producto_solicitado = models.ForeignKey(Producto, on_delete=models.CASCADE)
    componente_solicitado = models.ForeignKey(Componente, on_delete=models.CASCADE)
    def __str__(self):
        return f"{self.producto_solicitado} - {self.componente_solicitado} "
    

gestionPedidos/Pedidos/forms.py
from django.forms import ModelForm
from .models import Componente,Producto,Pedido,Cliente,ProductoPedido

class PedidoForm(ModelForm):
 class Meta:
    model = Pedido
    fields = ('codigo_referencia', 'fecha', 'cliente', 'preciototal')

class ComponenteForm(ModelForm):
 class Meta:
    model = Componente
    fields = '__all__'

class ProductoForm(ModelForm):
 class Meta:
    model = Producto
    fields = '__all__'

class ClienteForm(ModelForm):
 class Meta:
    model = Cliente
    fields = '__all__'

class ProductoPedidoForm(ModelForm):
 class Meta:
    model = ProductoPedido
    fields = '__all__'

gestionPedidos/Pedidos/views.py
from django.http import JsonResponse
from .models import Producto, Pedido,Componente, Cliente,ProductoPedido
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from Pedidos.forms import PedidoForm, ClienteForm,ComponenteForm,ProductoForm,ProductoPedidoForm
from django.shortcuts import render
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404

# LLamada a la pagina principal
def index(req):    
    return render(req,"index.html")

# Detalle de Pedidos
class PedidoDetailView(DetailView):
    model = Pedido
    template_name = 'pedido_detail.html'



# Listado de Pedidos
class PedidoListView(ListView):
    model = Pedido
    queryset = Pedido.objects.order_by('id')
    context_object_name = 'listado_pedidos'
    template_name = 'pedido_list.html'
    paginate_by = 3 

    def get_queryset(self):
        queryset = super().get_queryset()
        codigo_referencia_query = self.request.GET.get('codigo_referencia')

        if codigo_referencia_query:
            queryset = queryset.filter(codigo_referencia__icontains=codigo_referencia_query)

        return queryset
    
#Creacion Pedidos
class PedidoCreateView(CreateView):
    model = Pedido
    form_class = PedidoForm
    template_name = 'pedido_create.html'
    success_url = reverse_lazy('listado_pedidos')    

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
#Borrado de los pedidos
class PedidoDeleteView(DeleteView):
    model = Pedido
    success_url = reverse_lazy('listado_pedidos')
    template_name = 'pedido_delete.html'
#Actualizar pedidos
class PedidoUpdateView(UpdateView):
    model = Pedido
    template_name = 'pedido_edit.html'
    success_url = reverse_lazy('listado_pedidos')
    fields = ['codigo_referencia', 'fecha', 'cliente', 'preciototal']




# Creacion de clientes 
class ClienteCreateView(CreateView):
    model = Cliente
    form_class = ClienteForm
    template_name = 'cliente_create.html'
    success_url = reverse_lazy('listado_clientes')    

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    


# Listado de Clientes
class ClienteListView(ListView):
    model = Cliente
    queryset = Cliente.objects.order_by('id')
    context_object_name = 'listado_clientes'
    template_name = 'cliente_list.html'
    paginate_by = 3  
    
    def get_queryset(self):
        queryset = super().get_queryset()
        cif_query = self.request.GET.get('cif')

        if cif_query:
            queryset = queryset.filter(cif__icontains=cif_query)

        return queryset

    

# Detalle de cada Cliente
class ClienteDetailView(DetailView):
    model = Cliente
    template_name = 'cliente_detail.html'


#Borrado del cliente
class ClienteDeleteView(DeleteView):
    model = Cliente
    success_url = reverse_lazy('listado_clientes')
    template_name = 'cliente_delete.html'
#Actualizacion del cliente
class ClienteUpdateView(UpdateView):
    model = Cliente
    template_name = 'cliente_edit.html'
    success_url = reverse_lazy('listado_clientes')
    fields = ['cif', 'nombre_empresa', 'direccion', 'datos_contacto']

   
   
# Creacion de clientes 
class ComponenteCreateView(CreateView):
    model = Componente
    form_class = ComponenteForm
    template_name = 'componente_create.html'
    success_url = reverse_lazy('listado_componentes')    

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    


# Listado de Componente
class ComponenteListView(ListView):
    model = Componente
    queryset = Componente.objects.order_by('id')
    context_object_name = 'listado_componentes'
    template_name = 'componente_list.html'
    paginate_by = 3 
    def get_queryset(self):
        queryset = super().get_queryset()
        componentes_codigo_referencia_query = self.request.GET.get('componentes_codigo_referencia')

        if componentes_codigo_referencia_query:
            queryset = queryset.filter(componentes_codigo_referencia__icontains=componentes_codigo_referencia_query)

        return queryset
    

# Detalle de cada Componente
class ComponenteDetailView(DetailView):
    model = Componente
    template_name = 'componente_detail.html'
#Borrado del componente
class ComponenteDeleteView(DeleteView):
    model = Componente
    success_url = reverse_lazy('listado_componentes')
    template_name = 'componente_delete.html'
#Actualizacion del componente
class ComponenteUpdateView(UpdateView):
    model = Componente
    template_name = 'componente_edit.html'
    success_url = reverse_lazy('listado_componentes')
    fields = ['componentes_codigo_referencia', 'nombre_modelo', 'marca']




# Detalle de productos
class ProductoDetailView(DetailView):
    model = Producto
    template_name = 'producto_detail.html'

# Listado de Productos
class ProductoListView(ListView):
    model = Producto
    queryset = Producto.objects.order_by('id')
    context_object_name = 'listado_productos'
    template_name = 'producto_list.html'
    paginate_by = 3 

    def get_queryset(self):
        queryset = super().get_queryset()
        referencia_query = self.request.GET.get('referencia')

        if referencia_query:
            queryset = queryset.filter(referencia__icontains=referencia_query)

        return queryset
    
    
#Creacion Productos
class ProductoCreateView(CreateView):
    model = Producto
    form_class = ProductoForm
    template_name = 'producto_create.html'
    success_url = reverse_lazy('listado_productos')    

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
#Borrado de los Productos
class ProductoDeleteView(DeleteView):
    model = Producto
    success_url = reverse_lazy('listado_productos')
    template_name = 'producto_delete.html'
#Actualizar productos
class ProductoUpdateView(UpdateView):
    model = Producto
    template_name = 'producto_edit.html'
    success_url = reverse_lazy('listado_productos')
    fields = ['referencia', 'precio', 'nombre', 'descripcion','categoria','componentes']
#Creacion ProductoPedido
class ProductoPedidoCreateView(CreateView):
    model = ProductoPedido
    form_class = ProductoPedidoForm
    template_name = 'productopedido_create.html'
    success_url = reverse_lazy('listado_pedidos')    

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)




def show_producto(request, producto_id):
    producto = get_object_or_404(Producto, pk=producto_id)
    componente =  producto.componente_set.all()
    context = { 'producto': producto, 'listado_componente' : componente }
    return render(request, 'componente_list.html', context)


def show_pedido(request, cliente_id):
    cliente = get_object_or_404(Cliente, pk=cliente_id)
    pedido =  cliente.pedido_set.all()
    context = { 'cliente': cliente, 'listado_pedidos' : pedido }
    return render(request, 'pedido_list.html', context)

def obtener_detalles_componente(request, id):
    try:
        componente = Componente.objects.get(id=id)
        detalles = {
            'id': id,
            'codigo_referencia': componente.componentes_codigo_referencia,
            'modelo': componente.nombre_modelo,
            'marca': componente.marca,
        }
        return JsonResponse(detalles)
    except Componente.DoesNotExist:
        return JsonResponse({'error': 'El componente no existe'}, status=404)

gestionPedidos/Pedidos/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>

    <link rel="stylesheet" href="{% static 'css/pedidos.css'%}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block titulo %}Gestor de Empleados{% endblock %}</title>
    <script src="https://kit.fontawesome.com/eb496ab1a0.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/grande.js' %}"></script>


</head>
<body>

    <header{% if request.path == '/' %} class="hero-header"{% endif %}>
        <nav class="navbar">
            <div class="navbar-logo">
                <a href="{% url 'index' %}"><img src="{% static 'imagenes/Logo.png' %}" alt="foto logo" width="100" /></a>
            </div>
            <div class="navbar-menu">
                <ul>
                    <li>
                        <a href="{% url 'listado_clientes' %}">Listado clientes</a>
                    </li>
                    <li>
                        <a href="{% url 'listado_pedidos' %}">Listado pedidos</a>
                    </li>
                    <li>
                        <a href="{% url 'listado_componentes' %}">Listado componentes</a>
                    </li>
                    <li>
                        <a href="{% url 'listado_productos' %}">Listado productos</a>
                    </li>
                </ul>
            </div>
            <div class="navbar-tamaño">
                <button id="aumentar-btn" class="button button-primary">Aumentar tamaño</button>
                <button id="disminuir-btn" class="button button-secondary">Disminuir tamaño</button>
            </div>
        </nav>

        {% if request.path == '/' %}
        <div class="hero-image">
            <h1>Deustronic Components S.L.</h1>
            <p class="hero-description">La comodidad en la puerta de tu casa</p>
        </div>
        {% endif %}
    </header>
    <main>
        {% block contenido %}{% endblock %}
    </main>
    <footer>
        <div class="footer-container">
            <div class="footer-row">
                <div class="footer-col">
                    <h4>Acerca de nosotros</h4>
                    <ul class="social-icons">
                        <li><a href="https://es-es.facebook.com/"><i class="fab fa-facebook-f"></i></a></li>
                        <li><a href="https://twitter.com/?lang=es"><i class="fab fa-twitter"></i></a></li>
                        <li><a href="https://www.instagram.com/"><i class="fab fa-instagram"></i></a>
                        </li>
                        <li><a href="https://www.linkedin.com/feed/"><i class="fab fa-linkedin-in"></i></a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>Enlaces útiles</h4>
                    <ul class="links">
                        <li>
                            <a href="{%url 'listado_clientes' %}">Listado clientes</a>
                        </li>
                        <li>
                            <a href="{% url 'listado_pedidos'  %}">Listado pedidos</a>
                        </li>
                        <li>
                            <a href="{% url 'listado_componentes'  %}">Listado componentes</a>
                        </li>
                        <li>
                            <a href="{%url 'listado_productos' %}">Listado productos</a>
                        </li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>Contacto</h4>
                    <ul class="contact-info">
                        <li><i class="fas fa-map-marker-alt"></i> C/ Madrid, 50 01003 VITORIA - GASTEIZ</li>
                        <li><i class="fas fa-envelope"></i> Deustronic@hotmail.com</li>
                        <li><i class="fas fa-phone"></i> (+34) 945 72 85 33</li>
                    </ul>
                </div>

            </div>
        </div>
        <div class="footer-bottom">
            <p>Derechos de autor © 2023 MiEmpresa. Todos los derechos reservados.</p>
        </div>
    </footer>
 
    <script src="{% static 'js/formulario.js' %}"></script>
    <script src="{% static 'js/formulariocomponente.js' %}"></script>
    <script src="{% static 'js/validar.js' %}"></script>
    <script src="{% static 'js/tabla.js' %}"></script>
    
</body>

</html>

gestionPedidos/Pedidos/templates/cliente_create.html
{% extends 'base.html' %}

{% block titulo %} Creacion del cliente {% endblock %}

{% block contenido %}
<div class="container">
  <h1>Crear Cliente</h1>
  <form method="post" onsubmit="return validarFormularioCIF()">
    {% csrf_token %}
    <div class="form-group" id="'id_cif'">
      {{ form.cif.label_tag }}
      {{ form.cif }}
    </div>
    <p id="resultcif"></p>
    <div class="form-group">
      {{ form.nombre_empresa.label_tag }}
      {{ form.nombre_empresa }}
    </div>
    <div class="form-group">
      {{ form.direccion.label_tag }}
      {{ form.direccion }}
    </div>
    <div class="form-group">
      {{ form.datos_contacto.label_tag }}
      {{ form.datos_contacto }}
    </div>
    <button type="submit" class="btn btn-primary">Crear</button>
  </form>
</div>

{% endblock %}

gestionPedidos/Pedidos/templates/cliente_delete.html
{% extends 'base.html' %}
{% block titulo %} Borrado del cliente {% endblock %}

{% block contenido %}
<div class="borrar">
  <h1>Eliminar cliente "{{ cliente.cif }}"</h1>
  <form method="post" class="delete-form">
    {% csrf_token %}
    <p>¿Estás seguro de que quieres eliminar este cliente?</p>
    <button type="submit" class="btn btn-danger btn-delete">Eliminar</button>
    <a href="{% url 'listado_clientes' %}" class="btn btn-secondary btn-cancel">Cancelar</a>
  </form>
</div>
{% endblock %}

gestionPedidos/Pedidos/templates/cliente_detail.html
{% extends 'base.html' %}
{% block titulo %} Detalle del cliente {% endblock %}

{% block contenido %}
<div class="menu">
    <div class="listado-header">
        <h1>Detalle del Cliente</h1>
    </div>
    <div class="listado-tabla">
        <table>
            <thead>
                <tr>

                    <th>ID</th>
                    <th>CIF</th>
                    <th>Nombre de empresa</th>
                    <th>Dirección</th>
                    <th>Datos de contacto</th>
                    <th>Borrar</th>
                    <th>Editar</th>

                </tr>
            </thead>
            <tbody>
                {% if cliente %}

                <tr>
                    <td>{{ cliente.id }}</td>
                    <td>{{ cliente.cif }}</td>
                    <td>{{ cliente.nombre_empresa }}</td>
                    <td>{{ cliente.direccion }}</td>
                    <td>{{ cliente.datos_contacto }}</td>
                    <td><a class="datos" href="{% url 'cliente_delete' pk=cliente.id %}">Borrar</a></td>
                    <td><a class="datos"href="{% url 'cliente_edit' pk=cliente.id %}">Editar</a></td>

                </tr>

                {% endif %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

gestionPedidos/Pedidos/templates/cliente_edit.html
{% extends 'base.html' %}

{% block titulo %} Creacion del cliente {% endblock %}

{% block contenido %}
<div class="container">
  <h1>Actualizar Cliente</h1>
  <form method="post" onsubmit="return ActualizarFormularioCIF()">
    {% csrf_token %}
    <div class="form-group" id="'id_cif'">
      {{ form.cif.label_tag }}
      {{ form.cif }}
    </div>
    <p id="resultcif"></p>
    <div class="form-group">
      {{ form.nombre_empresa.label_tag }}
      {{ form.nombre_empresa }}
    </div>
    <div class="form-group">
      {{ form.direccion.label_tag }}
      {{ form.direccion }}
    </div>
    <div class="form-group">
      {{ form.datos_contacto.label_tag }}
      {{ form.datos_contacto }}
    </div>
    <button type="submit" class="btn btn-primary">Actualizar</button>
  </form>
</div>
{% endblock %}

gestionPedidos/Pedidos/templates/componente_delete.html
{% extends 'base.html' %}
{% block titulo %} Borrado del componente {% endblock %}

{% block contenido %}
<div class="borrar">
  <h1>Eliminar componente"{{ componente.componentes_codigo_referencia }}"</h1>
  <form method="post" class="delete-form">
    {% csrf_token %}
    <p>¿Estás seguro de que quieres eliminar este componente?</p>
    <button type="submit" class="btn btn-danger btn-delete">Eliminar</button>
    <a href="{% url 'listado_componentes' %}" class="btn btn-secondary btn-cancel">Cancelar</a>
  </form>
</div>

{% endblock %}

gestionPedidos/Pedidos/templates/componente_edit.html
{% extends "base.html" %}

{% block titulo %} Edit del componentes {% endblock %}

{% block contenido %}
<div class="container">
    <h1>Editar Componente "{{ componente.componentes_codigo_referencia }}"</h1>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form.componentes_codigo_referencia.label_tag }}
            {{ form.componentes_codigo_referencia }}
        </div>
        <div class="form-group">
            {{ form.nombre_modelo.label_tag }}
            {{ form.nombre_modelo }}
        </div>
        <div class="form-group">
            {{ form.marca.label_tag }}
            {{ form.marca }}
        </div>
        <button type="submit" class="btn btn-primary">Actualizar</button>
    </form>
</div>
{% endblock %}

gestionPedidos/Pedidos/templates/componente_list.html
{% extends "base.html" %}

{% block titulo %}Listado de componentes{% endblock %}

{% block contenido %}
<div class="listado-header">
    <h1>Listado de Componentes</h1>
</div>
<div class="buscador">
    <form method="GET">
        <input type="text" name="componentes_codigo_referencia" placeholder="Buscar Codigo Refrencia">
        <input type="submit" value="Buscar">
    </form>
</div>
<div class="listado-tabla">
    {% if listado_componentes %}
    <table id="tabla-componentes">
        <thead>
            <tr>
                <th>ID</th>
                <th>Codigo Referencia</th>
                <th>Ver Detalle</th>
                <th>Borrar</th>
                <th>Editar</th>
            </tr>
        </thead>

        <tbody>
            {% for componente in listado_componentes %}
            <tr>
                <td>{{ componente.id }}</td>
                <td>{{ componente.componentes_codigo_referencia }}</td>
                <td><button class="detail_button">Detalle</td>
                <td><a class="datos" href="{% url 'componente_delete' pk=componente.id %}">Borrar</a></td>
                <td><a class="datos" href="{% url 'componente_edit' pk=componente.id %}">Editar</a></td>
            </tr>
            {% endfor %}
            <tr id="fila-nueva" style="display: none;"></tr>
        </tbody>
    </table>
    {% else %}
    <p>No hay componentes creados.</p>
    {% endif %}
</div>
{% if is_paginated %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">Anterior</a>
        {% endif %}
        <span class="current-page">
            Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
        </span>
        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
        {% endif %}
    </span>
</div>
{% endif %}
<div class="crear-componente">
    <a class="crear" href="{% url 'componente_create' %}">Crear nuevo componente</a>
</div>

{% endblock %}

gestionPedidos/Pedidos/templates/pedido_detail.html
{% extends 'base.html' %}
{% block titulo %} Detalle del pedido {% endblock %}

{% block contenido %}
<div class="menu">
    <div class="listado-header">
        <h1>Detalle del pedido</h1>
    </div>
    {% if pedido.producto.all %}
    <div class="listado-tabla">
        <table>
            <thead>
                <tr>
                    <th>Pedido referencia</th>
                    <th>Producto referencia</th>
                    <th>Producto</th>
                    <th>Cantidad</th>
                    <th>Precio Unitario</th>
                    <th>Volver</th>
                </tr>
            </thead>
            {% for producto_pedido in pedido.productopedido_set.all %}
            <tbody>
                <tr>
                    <td>
                        {{ producto_pedido.pedido_solicitado.codigo_referencia }}
                    </td>
                    <td>
                        {{ producto_pedido.producto_solicitado.referencia }}
                    </td>
                    <td>
                        {{ producto_pedido.producto_solicitado.nombre }}
                    </td>
                    <td>
                        {{ producto_pedido.cantidad }}
                    </td>
                    <td>
                        {{ producto_pedido.producto_solicitado.precio }}
                    </td>
                    <td><a class="datos" href="{% url 'listado_pedidos'%}">Volver</a></td>
                </tr>
            </tbody>
            {% endfor %}
        </table>
    </div>
    {% else %}
    <p>No hay productos asociados.</p>
    {% endif %}
</div>
{% endblock %}

gestionPedidos/Pedidos/templates/precio_edit.html
{% extends "base.html" %}

{% block titulo %} Edit del precio {% endblock %}

{% block contenido %}
<div class="container">
    <h1>Editar precio "{{ precio.precio_total }}"</h1>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form.producto_solicitado.label_tag }}
            {{ form.producto_solicitado }}
        </div>
        <div class="form-group">
            {{ form.pedido_solicitado.label_tag }}
            {{ form.pedido_solicitado }}
        </div>
        <div class="form-group">
            {{ form.precio_total.label_tag }}
            {{ form.precio_total }}
        </div>
        <button type="submit" class="btn btn-primary">Actualizar</button>
    </form>
</div>
{% endblock %}

gestionPedidos/Pedidos/templates/producto_create.html
{% extends 'base.html' %}
{% block titulo %} Creacion del producto {% endblock %}
{% block contenido %}
<div class="container">
    <h1>Crear Producto</h1>

    <form method="post" onsubmit="return validarFormularioPrecio() ">
        {% csrf_token %}
        <div class="form-group">
            {{ form.referencia.label_tag }}
            {{ form.referencia }}
        </div>
        <div class="form-group">
            {{ form.precio.label_tag }}
            {{ form.precio }}
        </div>
        <p id="resultadoprecio"></p>
        <div class="form-group">
            {{ form.nombre.label_tag }}
            {{ form.nombre }}
        </div>
        <div class="form-group">
            {{ form.descripcion.label_tag }}
            {{ form.descripcion }}
        </div>
        <div class="form-group">
            {{ form.categoria.label_tag }}
            {{ form.categoria }}
        </div>
        <div class="form-group">
            {{ form.componentes.label_tag }}
            {{ form.componentes }}
        </div>
        
        
        <button type="submit" class="btn btn-primary">Enviar</button>
    </form>
</div>

{% endblock %}